"""
ASCII art assets
"""

# Viewserspace logo
# Generated by https://patorjk.com/software/taag
# Font: Cybermedium

VIEWSERSPACE_LOGO = """
_  _ _ ____ _ _ _ ____ ____ ____ ____ ___  ____ ____ ____ 
|  | | |___ | | | [__  |___ |__/ [__  |__] |__| |    |___ 
 \/  | |___ |_|_| ___] |___ |  \ ___] |    |  | |___ |___ 

"""
