name: ci
on:
   push:
      branches: master
jobs:
   build-and-deploy:
      runs-on: ubuntu-latest
      name: "Build and deploy to pypi"
      steps:
         - uses: actions/checkout@v2

         - uses: actions/setup-python@v2
           with:
              python-version: "3.8"
              architecture: "x64"

         - name: "Dependencies"
           run: |
              pip install poetry twine

         - name: "Build"
           run: poetry build 

         - name: "Publish"
           run: |
              twine upload dist/* --username __token__ --skip-existing --password ${{ secrets.PYPI_API_TOKEN }}


